version: "2"

run:
  timeout: 5m
  go: "1.25.6"

linters:
  enable:
    - errcheck
    - govet
    - ineffassign
    - staticcheck
    - unused
    - misspell
    - revive
    - gosec
    - unconvert
    - gocritic
    - prealloc
  settings:
    govet:
      enable-all: true
    revive:
      rules:
        - name: exported
          disabled: false
    gosec:
      excludes:
        - G204

formatters:
  enable:
    - gofmt
    - goimports
  settings:
    gofmt:
      simplify: true

issues:
  uniq-by-line: true
